/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.tcpclient2023;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author skaya
 */
public class Frm_Client extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Server
     */
    Client client;

    public static DefaultListModel lst_messagesFromServer_model = new DefaultListModel();

    public Frm_Client() {
        initComponents();
        this.lst_messagesFromServer.setModel(lst_messagesFromServer_model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_serverPort = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_messagesFromServer = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txta_messageToServer = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btn_stopConnection = new javax.swing.JButton();
        btn_startConnection = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_sendMessageBroadcast = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_serverAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_serverPort.setText("5000");
        getContentPane().add(txt_serverPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jScrollPane2.setViewportView(lst_messagesFromServer);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 340, 120));

        txta_messageToServer.setColumns(20);
        txta_messageToServer.setRows(5);
        jScrollPane3.setViewportView(txta_messageToServer);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel1.setText("Server Port");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, -1));

        btn_stopConnection.setText("Stop");
        btn_stopConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stopConnectionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_stopConnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 75, -1));

        btn_startConnection.setText("Start");
        btn_startConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startConnectionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_startConnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 70, -1));

        jLabel2.setText("Message");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, -1));

        jLabel3.setText("Messages");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 80, -1));

        btn_sendMessageBroadcast.setText("Send Message");
        btn_sendMessageBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendMessageBroadcastActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sendMessageBroadcast, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 230, -1));

        jLabel5.setText("Server Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txt_serverAddress.setText("127.0.0.1");
        getContentPane().add(txt_serverAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startConnectionActionPerformed
        try {
            // TODO add your handling code here:
            String serverAddress = txt_serverAddress.getText();
            String port = txt_serverPort.getText();
            
            this.client= new Client(serverAddress, Integer.parseInt(port));
            this.client.Listen();
        } catch (IOException ex) {
            Logger.getLogger(Frm_Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_startConnectionActionPerformed

    private void btn_stopConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stopConnectionActionPerformed
        // TODO add your handling code here:
        this.client.Stop();
    }//GEN-LAST:event_btn_stopConnectionActionPerformed

    private void btn_sendMessageBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendMessageBroadcastActionPerformed
        try {
            // TODO add your handling code here:
            String message= txta_messageToServer.getText();
            this.client.SendMessage(message.getBytes());
        } catch (IOException ex) {
            Logger.getLogger(Frm_Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_sendMessageBroadcastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sendMessageBroadcast;
    private javax.swing.JButton btn_startConnection;
    private javax.swing.JButton btn_stopConnection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lst_messagesFromServer;
    private javax.swing.JTextField txt_serverAddress;
    private javax.swing.JTextField txt_serverPort;
    private javax.swing.JTextArea txta_messageToServer;
    // End of variables declaration//GEN-END:variables
}
